apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: short
  name: short
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: short
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: short
    spec:
      containers:
        - image: registry.cloud.okteto.net/tullo/short:okteto
          imagePullPolicy: Always
          name: short
          command:
            - short
            - -b
            - :8080
            - -c
            - $(connstring) # env var expansion
            - --httpOnly
          env:
            - name: connstring
              valueFrom:
                secretKeyRef:
                  key: connstring
                  name: short-secrets
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz?ready=1
              port: http
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          volumeMounts:
            - mountPath: "/secrets"
              name: secrets
      dnsPolicy: ClusterFirst
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: secrets
          secret:
            secretName: short-secrets
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: short
  name: short
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: short
  type: ClusterIP
